#########################################################################
# Title:         Cloudbox: NZBGet - Scripts Task                        #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: Scripts | Create nzbget script directories
  file: "path={{ item }} state=directory mode=0775 owner={{ user.name }} group={{ user.name }}"
  with_items:
    - /opt/scripts/nzbget
    - /opt/scripts/nzbget/nzbgetpp

- name: Scripts | Download various scripts
  get_url:
    url:  "{{ item }}"
    dest: "/opt/scripts/nzbget/"
    mode: 0775
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    force: yes
    validate_certs: no
  with_items:
    - "https://raw.githubusercontent.com/clinton-hall/GetScripts/master/flatten.py"
    - "https://raw.githubusercontent.com/clinton-hall/GetScripts/master/DeleteSamples.py"
    - "https://raw.githubusercontent.com/Prinz23/nzbget-pp-reverse/master/reverse_name.py"
  ignore_errors: yes

- name: Scripts | Download unzip.py script
  git:
    repo: "https://github.com/Prinz23/nzbgetpp.git"
    dest: "/opt/scripts/nzbget/nzbgetpp/"
    clone: yes
    version: HEAD
    force: yes
  become: yes
  become_user: "{{ user.name }}"
  register: unzip_py
  ignore_errors: yes

- name: Scripts | Add unrar path to rarfile.py
  lineinfile:
    path: "/opt/scripts/nzbget/nzbgetpp/rarfile/rarfile.py"
    regexp: '^UNRAR_TOOL\s?=.*'
    line: 'UNRAR_TOOL = "/app/unrar"'
    state: present
  when: unzip_py is success

- name: Scripts | Import HashRenamer.py
  copy:
    src: "HashRenamer.py"
    dest: "/opt/scripts/nzbget/HashRenamer.py"
    owner: "{{ user.name }}"
    group: "{{ user.name }}"
    mode: 0775
    force: yes
