#########################################################################
# Title:         Cloudbox: Settings Role                                #
# Author(s):     l3uddz, desimaniac                                     #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Settings: Start"
  include_tasks: "subtasks/start.yml"

- name: "Settings: Ansible Config"
  include_tasks: "subtasks/ansible_config.yml"
  with_items:
    - "ansible.cfg"

- name: "Setting: Settings Migrator"
  include_tasks: "subtasks/settings_migrator.yml"
  with_items:
    - "accounts.yml"
    - "settings.yml"
    - "adv_settings.yml"
    - "backup_config.yml"

- name: Initialize empty lists and vars
  set_fact:
    files_updated_successfully: []
    files_updated_unsuccessfully: []
    exit_is_necessary: false

- name: "Setting: Settings Updater"
  include_tasks: "subtasks/settings_updater.yml"
  with_items:
    - "accounts.yml"
    - "settings.yml"
    - "adv_settings.yml"
    - "backup_config.yml"

- name: "Settings: Finish"
  include_tasks: "subtasks/finish.yml"
