#########################################################################
# Title:         Cloudbox: Settings | Copy                              #
# Author(s):     desimaniac                                             #
# URL:           https://github.com/cloudbox/cloudbox                   #
# --                                                                    #
#         Part of the Cloudbox project: https://cloudbox.works          #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
# Check for config files and import they are missing
- name: "Copy | Check if '{{ file }}' exists"
  stat:
    path: "{{ playbook_dir }}/{{ file }}"
  register: file0

- name: "Copy | Copy '{{ file }}.default' to '{{ file }}'"
  copy:
    src: "{{ playbook_dir }}/defaults/{{ file }}.default"
    dest: "{{ playbook_dir }}/{{ file }}"
    owner: "{{ cloudbox_yml.stat.uid }}"
    group: "{{ cloudbox_yml.stat.gid }}"
    mode: 0664
  when: not file0.stat.exists
